name: catatan_keuangan
description: Aplikasi untuk mencatat pemasukan dan pengeluaran secara praktis.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.2.0
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^0.13.6
  crypto: ^3.0.3
  intl: ^0.18.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-catke.png

flutter_launcher_icons:
  image_path: "assets/images/logo-catke.png"
  android: true
  ios: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
